### ISSUE TITLE
关于添加aria2c和IDM的想法

### ISSUE THREAD

**Issue by sequencer** [Accelerider/BaiduPanDownloadWinform#102]
感觉下载管理有种不需要的感觉。
能不能直接连接到aria直接下载了？
或者做成chrome的插件以支持Linux和Mac系统有可能嘛？

感觉原理上的实现就是使用了API然后传cookies直连下载。

**Comment by caoli5288** [comment]
并不。你可以试试aria2c的速度，感人。

**Comment by sheng0325** [comment]
我把aria下载的文件拉进下载器，版本无法支持，为什么呢？
