### ISSUE TITLE
1.7.8版本不能按照目录原本的结构下载了吗

### ISSUE THREAD

**Issue by ybxb** [Accelerider/BaiduPanDownloadWinform#85]
下载下来的文件全都在同一个文件夹里，没有按照目录原本的结构下载，请问这是个例吗？
![2016-12-05-121635](https://cloud.githubusercontent.com/assets/14197424/20873899/7cf1fe8a-bae7-11e6-97e2-121a57205e5a.png)
![2016-12-05-1211](https://cloud.githubusercontent.com/assets/14197424/20873774/316ba5ac-bae6-11e6-9ca5-4458530ed8db.png)

**Comment by Mrs4s** [comment]
是bug 下个版本修复
因为1.7.7的时候重写了添加下载的代码 没有加上目录判断

**Comment by ThinWonton** [comment]
哭死了   没有目录

**Comment by shineme** [comment]
还没修复。。
